### PR TITLE
Change pink

### PR DESCRIPTION
**Pull request by cmaimone**
Previewed locally

* Changes pink color throughout.
* Changes logo file
* Changes favicon
* Removes un-used (hopefully) files from assets/img

Addresses issue #103 and partially issue #104

### CODE REVIEW

**Comment by cmaimone** [comment]
favicon might be too small - I can instead do a full square with the updated color/font instead of the callout (which isn't square, and makes the text a little squishy

**Comment by cmaimone** [comment]
Do we care about the url-checker?  This time, it's erasing @vsoch !!! ( https://stanford-rc.github.io/rse-services/ is gone)

**Comment by vsoch** [comment]
I single-handedly ran rse-services, so it's about time (and kind of sad too) that it's finally removed. :cry:

**Comment by vsoch** [comment]
I would remove it from wherever it's hitting, it's definitely a correct hit at this point.

**Review by vsoch — APPROVED** [review]
This looks so much better! Phew, let's get rid of that pink asap :laughing: 

image

**Pull request merged**
