### PR TITLE
Main box logo update

### LINKED ISSUE #104: Icon in What is US-RSE? main page box and favicon
Change from old logo element to something new

### PR DESCRIPTION
**Pull request by cmaimone**
Updates the logo image in one of the boxes on the main page

Previewed locally

Closes #104

### CODE REVIEW

**Comment by cosden** [comment]
Ah, @cmaimone. I think I see the issue. Does this include all the commits from #109 too?

**Comment by cosden** [comment]
I like the circular logo! Looks great!

image

**Comment by cmaimone** [comment]
If I just squash and merge, will this one be ok?  It does include previous changes - I did something wrong

**Comment by cmaimone** [comment]
I tried squash and merge on another PR with this - let's see how that goes?

**Review by cosden — APPROVED** [review]
@cmaimone, go for it. You could rebase, but I think because it'll be ok to squash and merge in this case. The commit history should be fine.

**Pull request merged**
