### PR TITLE
Update/event layout

### LINKED ISSUE #10: Event page layout
I like the event page layout, and the categorization approach, but it does lose the chronological view. Perhaps the calendar is sufficient for this. Still, I think this is a good issue for discussion - what should the event page look like.

### PR DESCRIPTION
**Pull request by exoticDFT**
Updates the layout of the events page and updates the event cards.

## Description

- Adds functionality to display only the upcoming events on the main events page.
- Updates the layout of the events page to display multiple events per row.
- Modifies the look of an event card. 

## Motivation and Context

Resolves #10 

## Checklist:

- [ ] I have posted the link for the PR in the usrse slack (#website) to ask for reviewers
- [x] I have previewed changes locally
- [x] I have updated the README.md if necessary

cc @usrse-maintainers

### CODE REVIEW

**Comment by exoticDFT** [comment]
These cards also affect the calendar page, which I realized only after I finally got all the design working. When I checked locally everything seemed to be working fine, but for whoever reviews this PR, we should make sure to check more than just the main event page in case I missed other locations this influenced. I believe it was only main events page and calendar though

**Comment by vsoch** [comment]
And don't worry about the fails - it looks like two sites having temporary issues (timeouts).

**Comment by exoticDFT** [comment]
> I'm wondering if we should hide categories for which there aren't recent events, e.g.,:

I was also thinking this, since we have a lot of empty space now. Shouldn't be too hard to add.

> And perhaps at the top we can make it easy to click on the same archive link for each event type?

I think this is a great idea. I should be able to add that quickly. I'll look into it as soon as I'm free.

**Comment by exoticDFT** [comment]
@vsoch What do you think of it now after those updates?
Screenshot from 2021-09-07 09-30-39

**Comment by vsoch** [comment]
Yep that looks good! It looks like we can go from this main page to the archive to see old events. The events categories page is also linked (bottom right of a category) and it might need a refactor / change in the future (it's a little strange having three pages now) but I think that's out of scope for this PR.

**Comment by exoticDFT** [comment]
Two comments to add:
1. Seems the only way to guarantee we aren't getting the wrong dates is to use "event.expires" variable. This works well, but may end up dropping the day of events from the list. I'm not sure the best way to resolve this potential "bug".
2. The current code has some redundancy in the two sections of code that figure out what are the categories and which events have passed. Since we don't run this is real time, it's not a big concern in terms of inefficiency. However, if we do ever change this functionality, we'll have to make sure both sections are adjusted as needed.

**Comment by exoticDFT** [comment]
> Yep that looks good! It looks like we can go from this main page to the archive to see old events. The events categories page is also linked (bottom right of a category) and it might need a refactor / change in the future (it's a little strange having three pages now) but I think that's out of scope for this PR.

I was also going to ask this question.
Do we want to update the "/events/category/" page to use the same format as this events page now? And/or do we even want to directly link to this at all if we have the "/events/archive/" page.

**Comment by vsoch** [comment]
1. @exoticDFT we could ask people to just add a day to the expires?
2. I think the redundancy is needed (I was looking at it earlier) because we can't know if a category is going to appear without looping through it once. Since it's a static site it's functionally not super different (e.g., we don't see the loops, just the rendered output). Agree that if there are changes both need to be updated. I guess the only question is if there is true replication, is there any way to merge into one include and use in both places, possibly with just a little different logic?

**Comment by vsoch** [comment]
> I was also going to ask this question. Do we want to update the "/events/category/" page to use the same format as this events page now? And/or do we even want to directly link to this at all if we have the "/events/archive/" page.

The purpose of this page was to show all events for a category, without filtering by date. I would say we'd want the same format, and to make it clear that it's showing expired events.

**Comment by exoticDFT** [comment]
>     1. @exoticDFT we could ask people to just add a day to the expires?
Right now there is generally only the "date" in the expires variable in any given event, i.e. "expires: 2021-10-06". I think we would need to make people also add the time. Maybe "force" people to use the [ISO8601 standard](https://en.wikipedia.org/wiki/ISO_8601) or something similar that may be more intuitive?

>     2. I think the redundancy is needed (I was looking at it earlier) because we can't know if a category is going to appear without looping through it once. Since it's a static site it's functionally not super different (e.g., we don't see the loops, just the rendered output). Agree that if there are changes both need to be updated. I guess the only question is if there is true replication, is there any way to merge into one include and use in both places, possibly with just a little different logic?
There is another way I've done this without the redundancy. Although I'm not sure it's much better. But that is to run through the categories once, check for the upcoming dates and storing them in another set of arrays containing only those upcoming events.

**Comment by exoticDFT** [comment]
> > I was also going to ask this question. Do we want to update the "/events/category/" page to use the same format as this events page now? And/or do we even want to directly link to this at all if we have the "/events/archive/" page.
> 
> The purpose of this page was to show all events for a category, without filtering by date. I would say we'd want the same format, and to make it clear that it's showing expired events.

Should I make this another PR or include the changes in this one? It was easy enough to update. Here are two screenshots 😄 

image

image

**Comment by vsoch** [comment]
Yeah let's push those here too, if it's easy enough!  What should the title be? Archive of Events by Category or something? Should there be some way to distinguish events visually that are expired? (e.g., slight change of the color of the headers?)

**Comment by exoticDFT** [comment]
> Yeah let's push those here too, if it's easy enough! What should the title be? Archive of Events by Category or something? Should there be some way to distinguish events visually that are expired? (e.g., slight change of the color of the headers?)

I updated the title to say (Upcoming, Current, and Past) but definitely up for a better title. The one you suggested sounds good to me. So I'll update to that.
I'm not sure how easy it'd be to change the colors, I can't remember if I left this easily adjustable or not. I think any event card has this specific color. But maybe I can find a way to gray the header if it's not upcoming or current.

**Comment by vsoch** [comment]
I think you'd want to do:

1. Assign some boolean to indicate if the event is expired (similar logic to before)
2. Add to this element, and just tweak the color to be something a little faded if it's expired `  <div class="card-header" style="color: #790c63; background-color: #790c63;">`

You probably don't need the boolean, the "if event is expired" check would suffice. But I think it should be fairly straight forward to do! Then I think this PR would be perfect. Let me know if/when you want me to pull to preview again.

**Comment by exoticDFT** [comment]
Like so?

image

I can definitely tweak the color. Just went with black because it was easy to remember as `#000000`

**Comment by vsoch** [comment]
Exactly! And for the color I'd just start with the current and look at the little color box thingy and drag it to be whatever is a little darker than that. if that doesn't look "expired" another option is to make the content box a slight off white.

**Comment by exoticDFT** [comment]
@vsoch Look "expired" enough?

image

**Comment by exoticDFT** [comment]
I look into trying to add a "key/legend" if we think that's useful

**Comment by vsoch** [comment]
yeah I think that's good! We can either get others' feedback first or I'm happy to just merge it - it looks great overall and I'm in triage mode to get this done.

**Comment by exoticDFT** [comment]
Oh one thing to note, this current functionality will make the calendar events grayed out if expired as well. Which I think is fine, but just wanted to point that out. Two examples:

image

image

**Comment by vsoch** [comment]
I think that's probably good : :)

**Comment by exoticDFT** [comment]
@vsoch Just pushed. I'm going to grab lunch, but if we need something else I can work on it later when I get back.

**Comment by vsoch** [comment]
Nope let's call this one done! Great work @exoticDFT !

**Pull request merged**
