### PR TITLE
Changes to News layout

### PR DESCRIPTION
**Pull request by cmaimone**
Starting this as a PR for discussion on code changes (not just theoretical discussion), since it involves several changes - not ready to merge yet.  

I've changed post.html, which @v mentioned elsewhere, might affect blog posts -- but I don't think we have blog posts anymore separate from news (but I could be missing something).  Main changes were to 
* display the subtitle for full post pages, since multiple posts have one -- especially newsletters (which can get a separate template if needed)
* change display of tags on full post and excerpt list
* change formatting of excerpts on the news list view

This is work on issue #58

### CODE REVIEW

**Comment by vsoch** [comment]
@cmaimone sorry I missed this, I'm unfortunately not just "v" on here (I think you might have pinged someone else though, haha). 

Looking now I think you are right - we've branded previous blog posts just as "news" here, and the special tag isn't news but "newsletter." So if you want to just go ahead and edit post.html, since nothing else uses it that would be okay with me.

**Comment by cmaimone** [comment]
I guess there's nothing major left - @vsoch or others, please take a look when you have a chance

**Comment by vsoch** [comment]
I really love this - I think it's a huge improvement and we should do the same for events! A quick few fixes before merge:

1. The top level link (News) currently goes to 404 (the url without the baseurl, which technically will be the root of the site when it's deployed, but I think we want it to go to /news

image

The top link there, "News"

2. Maybe for the post page, the publish date can be italic?
image

3. It would be good to have a little more space between the very top post and the top navigation, here:

image

**Review by vsoch — APPROVED** [review]
I think this is good to go, let's merge.

**Pull request merged**
