### PR TITLE
Explain more about why to join US-RSE.

### LINKED ISSUE #17: Join page: add it's free, content
Refine the text on the Join page.  In particular:
* Note that it's currently free
* What do members get?  add in they'll get newsletters, vote for SC, etc.
* Who should join: both RSEs and allies

### PR DESCRIPTION
**Pull request by mtbc**
## Description
* One gets newsletters.
* One gets to vote.
* We're a broad tent.
* It's free!

## Motivation and Context
Fixes #17.

## Checklist:
- [ ] I have posted the link for the PR in the usrse slack (#website) to ask for reviewers
- [x] I have previewed changes locally
- [ ] I have updated the README.md if necessary

cc @usrse-maintainers

### CODE REVIEW

**Comment by cmaimone** [comment]
We don't need to update the jobs page at this point -- something we'll need to do at the end.  The join page can get merged though (I did not preview the change I made).

**Comment by mtbc** [comment]
Thank you @cmaimone, should I keep the "for free" below as well?

**Comment by mtbc** [comment]
Ah, yeah, the jobs page gave me unhappy CI so I was going for the green checkmark.

**Comment by cmaimone** [comment]
I think "free" is fine in both places, but it's your call

**Pull request merged**
