### PR TITLE
Issue #78: Fixes URL of sidebar menu title

### LINKED ISSUE #78: Bug: Sidebar menu labels (top link) link to vsoch.github.io
The news link in the top left of the news related pages goes to the wrong location.

image

### PR DESCRIPTION
**Pull request by exoticDFT**
Fixes #78 with URL correction

## Description

- Updates the sidebar menu title to use the baseurl and menubar variables for the sidebar menu title URL.
- Updates some formatting.

## Motivation and Context

Was an issue that needed to be addressed

## Checklist:

- [ ] I have posted the link for the PR in the usrse slack (#website) to ask for reviewers
- [x] I have previewed changes locally
- [x] I have updated the README.md if necessary

cc @usrse-maintainers

### CODE REVIEW

**Comment by vsoch** [comment]
@exoticDFT if you can confirm this works locally, happy to merge!

**Comment by exoticDFT** [comment]
@vsoch It worked on my local machine doing the basic jekyll serve command 😄

**Review by vsoch — APPROVED** [review]
Then LGTM! The changes to jinja look good so I'm happy to merge :) Thank you @exoticDFT !

**Comment by exoticDFT** [comment]
Thanks @vsoch! Although now that it is merged, it seems there is a mistake with the join sidebar menu. I'll take a look.

**Comment by vsoch** [comment]
ohno, I thought you said it was okay :( If you don't have a fix quickly, I can revert the PR here, no harm done.

**Comment by vsoch** [comment]
Just a quick tip - if you want a link to just point to the page it's on, just put `#`

**Comment by exoticDFT** [comment]
@vsoch Sorry about that. I swear I checked all the pages and things were working, but I must have missed the "join/engage" pages/sidebar menus. Your idea of "#" would be the best solution if we are trying to have the sidebar menu title lead you to the page you're already on. I feel like if that is the plan, we might as well not make the title a link?

So I'm thinking one of two options to quickly fix this. One, we do not make these titles a clickable link. Two, we keep the clickable link and rename the sidebar menu for the "Get Involved" pages to match its name. "Get Involved" is the topbar menu title and the header of the "Engage" page. The second option breaks the directory structure naming though, which is "engage"... So maybe third option is rename the topbar menu item and "Engage" page's header to "Engage".

**Comment by vsoch** [comment]
I think we'd want to make it clickable, because some people would be inclined to right click to copy it and send to someone.

How about just renaming everything to Get Involved? I do think we'd want to match what we have with the current side (but the Jean Luke Picard reference "Engage!" is pretty funny too :P

**Pull request merged**
