### PR TITLE
Addressing early issues with navigation and links

### LINKED ISSUE #4: US-RSE Association & Home in nav bar
Do we need them both? They seem to serve the same function.

### LINKED ISSUE #5: Spelling out of US-RSE Association
I realize the first time we see the US-RSE abbreviation is after the header and the events/about/news section. I'm not sure we're quite ready to assume people will know that's what it means. So maybe there is a way to work it in higher up.

### LINKED ISSUE #6: News link & front page display
I feel that news & updates (using the old site's terminology - not necessarily how we have to continue) is important and a key way we communicate timely and pertinent organization information.
Right now the news link (learn more) goes to newsletters rather than news and updates and the reader would have to notice the side menu. I think either going to news & updates first would be better. Or rethinking the way news & updates is displayed/linked on the front page.

### LINKED ISSUE #13: Copyright and CC BY
On the old page we had a footer that made this explicit:
image
I think we should have something similar (but where?!)

### PR DESCRIPTION
**Pull request by vsoch**
This is a quick PR to start grabbing some of the issues on the board. 

1. Remove extra "Home" in navigation bar (fix #4)
1. add the usrse copyright back to the bottom (fix #13)
2. change the home callouts for news to link to news instead of newsletters (fix #6)
3. update the hero text to include the full usrse name (fix #5)

I hope that others can also assign themselves to some issues too!

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

## Checklist:

- [ ] I have posted the link for the PR in the usrse slack (#website) to ask for reviewers
- [ ] I have previewed changes locally
- [ ] I have updated the README.md if necessary

cc @usrse-maintainers

### CODE REVIEW

**Review by cosden — APPROVED** [review]
Looks good! I think this fixes/addresses everything nicely. It should close all the issues, but I think we should keep two open for 
1. #13: Licensing content with CC BY 4.0. (Does this warrant a larger discussion?)
2. #6: Are we doing the right thing with displaying news?

**Comment by vsoch** [comment]
I think the licensing bit warrants further discussion - I don't recall when/why it was added, but it seems weird that we need to license the content on our site. There are probably two things in question - the _content_ of the site and then the _template_ itself (which is covered by the LICENSE in the repository). But honestly it looks weird to have a license for content. I would say that the content should just fall under the same license as the repository, and if someone copies it, that's still plagarism. So - a new issue that discusses why this license is needed for the content and convinces the majority to keep it I think is warranted.

**Comment by vsoch** [comment]
Anyway, feel free to merge @cosden.

**Comment by cosden** [comment]
I believe the decision was made to license freely (with attribution) the content so that people could cross post our "blog" type news/updates elsewhere. Let's punt on it for now. It can be completely divorced from the rest of the website redesign discussion (I think).

**Pull request merged**
